spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    mongodb:
      port: 27017
      database: tacoclouddb

de:
  flapdoodle:
    mongodb:
      embedded:
        version=: 4.16.2
server:
  port: 8081